# Generated by Django 5.2.7 on 2025-11-03 08:34

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
        ("wagtailcore", "0095_groupsitepermission"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("hero_banner", 5),
                    ("mission_vision", 11),
                    ("impact_stats", 18),
                    ("featured_programs", 25),
                    ("testimonial_carousel", 30),
                    ("news_updates", 32),
                    ("call_to_action", 35),
                    ("partner_logos", 37),
                    ("contact_form", 39),
                    ("video_highlight", 41),
                    ("donation_progress", 43),
                    ("map_location", 44),
                    ("spacer", 46),
                    ("divider", 47),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title of the hero banner", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Subtitle of the hero banner", "required": False},
                    ),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Image of the hero banner", "required": True},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Call to action button text", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Call to action button URL", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("subtitle", 1),
                                ("image", 2),
                                ("cta_button", 3),
                                ("cta_button_url", 4),
                            ]
                        ],
                        {},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title of the mission section", "required": True},
                    ),
                    7: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Content of the mission section",
                            "required": True,
                        },
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title of the vision section", "required": True},
                    ),
                    9: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Content of the vision section",
                            "required": True,
                        },
                    ),
                    10: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Illustration of the mission and vision section",
                            "required": True,
                        },
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("mission_title", 6),
                                ("mission_content", 7),
                                ("vision_title", 8),
                                ("vision_content", 9),
                                ("illustration", 10),
                            ]
                        ],
                        {},
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Title of the impact stats section",
                            "required": True,
                        },
                    ),
                    13: ("wagtail.blocks.CharBlock", (), {}),
                    14: ("wagtail.blocks.IntegerBlock", (), {}),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 13), ("value", 14)]],
                        {},
                    ),
                    16: ("wagtail.blocks.ListBlock", (15,), {}),
                    17: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("light", "Light"),
                                ("dark", "Dark"),
                                ("themed", "Themed"),
                            ]
                        },
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 12), ("stats", 16), ("background_style", 17)]],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Title of the feature programs section",
                            "required": True,
                        },
                    ),
                    20: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    21: ("wagtail.blocks.TextBlock", (), {}),
                    22: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("program_image", 20),
                                ("program_title", 13),
                                ("program_description", 21),
                                ("program_link", 22),
                            ]
                        ],
                        {},
                    ),
                    24: ("wagtail.blocks.ListBlock", (23,), {}),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [[("section_title", 19), ("programs", 24)]],
                        {},
                    ),
                    26: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    27: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 13), ("quote", 21), ("photo", 27)]],
                        {},
                    ),
                    29: ("wagtail.blocks.ListBlock", (28,), {}),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [[("section_title", 26), ("testimonials", 29)]],
                        {},
                    ),
                    31: ("wagtail.blocks.IntegerBlock", (), {"default": 3}),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [[("section_title", 26), ("number_of_articles", 31)]],
                        {},
                    ),
                    33: ("wagtail.blocks.TextBlock", (), {"required": True}),
                    34: ("wagtail.blocks.PageChooserBlock", (), {"required": True}),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 26),
                                ("text", 33),
                                ("button_text", 26),
                                ("button_link", 34),
                                ("background_image", 27),
                            ]
                        ],
                        {},
                    ),
                    36: ("wagtail.blocks.ListBlock", (20,), {}),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 26), ("logos", 36)]],
                        {},
                    ),
                    38: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 26), ("intro_text", 38)]],
                        {},
                    ),
                    40: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 26), ("video_url", 40), ("caption", 38)]],
                        {},
                    ),
                    42: ("wagtail.blocks.IntegerBlock", (), {"required": True}),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 26), ("goal_amount", 42), ("current_amount", 42)]],
                        {},
                    ),
                    44: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 26), ("map_embed_url", 40)]],
                        {},
                    ),
                    45: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small"),
                                ("medium", "Medium"),
                                ("large", "Large"),
                            ]
                        },
                    ),
                    46: ("wagtail.blocks.StructBlock", [[("height", 45)]], {}),
                    47: ("wagtail.blocks.StructBlock", [[]], {}),
                },
            ),
        ),
        migrations.CreateModel(
            name="ArticlePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("date", models.DateField(verbose_name="Published date")),
                ("intro", models.CharField(max_length=250)),
                ("body", wagtail.fields.RichTextField(blank=True)),
                (
                    "featured_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("website", models.URLField(blank=True)),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partner Organization",
                "verbose_name_plural": "Partner Organizations",
            },
        ),
        migrations.CreateModel(
            name="ProgramPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("description", wagtail.fields.RichTextField(blank=True)),
                ("contact_link", models.URLField(blank=True)),
                (
                    "featured_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("quote", models.TextField()),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
            },
        ),
    ]
